void lift_PID();
void lift_controller_initialize();
void lift_control_task();
void lift_movement_up();
void lift_movement_down();
void scoring_roller();
void score();
extern int liftStage;
extern double current_height;
extern double target_height;
